set PHASE=developement
set MONGOLAB_URI=mongodb://localhost:27017/ln_banking
set ENCRYPTED_KEY=FZDHuXvT2bSp5Mh4aDxUGFtHpnnnOOAa3WIDTMfuqSU_MMaa=
set JWT_SECRATE=ttJJHSH_2NNDH8ndjddd_kk-dky89lddowbddddvdiwodmd=
set SERVING_PORT=8085
